# # version: '3.9'

# services:
#   backend:
#     build:
#       context: ./backend
#     # image: "${USERNAME}/${BACKEND}:${TAG}" # Backend image  
#     ports:
#       - "5000:5000"
#     environment:
#       - MYSQL_HOST=db
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=password
#       - MYSQL_DATABASE=counter_app
#       - PLUGIN_HOST=plugin
#       - PLUGIN_PORT=50051
#     depends_on:
#       - db

#   frontend:
#     build:
#       context: ./frontend
#     # image: "${USERNAME}/${FRONTEND}:${TAG}" # Frontend image  
#     ports:
#       - "3000:3000"
#     depends_on:
#       - backend

#   db:
#     image: mysql:8.0
#     # image: arm64v8/mysql:8.0  # Use ARM-specific image for ARM systems
#     # platform: linux/arm64     # Ensure the correct platform is used
#     container_name: mysql_db
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#       MYSQL_DATABASE: counter_app
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
  
#   plugin:
#     build:
#       context: ./plugin
#     # image: "${USERNAME}/${PLUGIN}:${TAG}" # Plugin image  
#     ports:
#       - "50051:50051"
#     environment:
#       - PLUGIN_PORT=50051
# volumes:
#   db_data:
version: '3.9'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=counter_app
      - PLUGIN_HOST=plugin
      - PLUGIN_PORT=50051
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - WDS_SOCKET_HOST=localhost
      - WDS_SOCKET_PORT=9000

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: counter_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  plugin:
    build:
      context: ./plugin
    ports:
      - "50051:50051"
    environment:
      - PLUGIN_PORT=50051

  nginx-gateway:
    container_name: nginx-gateway
    image: nginx:stable-bullseye
    ports:
      - "9000:9000" # Change port if necessary
    volumes:
      - ./nginx_gateway_development.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
      - plugin

volumes:
  db_data:



